name: Build Simple BitChat APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create minimal working project
      run: |
        # Create a basic working Android project structure
        mkdir -p app/src/main/java/com/bitchat/android
        
        # Create minimal MainActivity
        cat > app/src/main/java/com/bitchat/android/MainActivity.kt << 'EOF'
        package com.bitchat.android
        
        import android.app.Activity
        import android.os.Bundle
        
        class MainActivity : Activity() {
            override fun onCreate(savedInstanceState: Bundle?) {
                super.onCreate(savedInstanceState)
                setContentView(android.R.layout.activity_list_item)
            }
        }
        EOF
        
        # Fix build.gradle to be minimal
        cat > app/build.gradle.kts << 'EOF'
        plugins {
            id("com.android.application")
            id("org.jetbrains.kotlin.android")
        }
        
        android {
            namespace = "com.bitchat.android"
            compileSdk = 33
        
            defaultConfig {
                applicationId = "com.bitchat.android"
                minSdk = 21
                targetSdk = 33
                versionCode = 1
                versionName = "1.0"
            }
        
            buildTypes {
                debug {
                    isMinifyEnabled = false
                }
            }
        
            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_1_8
                targetCompatibility = JavaVersion.VERSION_1_8
            }
            
            kotlinOptions {
                jvmTarget = "1.8"
            }
        }
        
        dependencies {
            implementation("androidx.core:core-ktx:1.9.0")
        }
        EOF
        
        # Fix project build.gradle
        cat > build.gradle.kts << 'EOF'
        plugins {
            id("com.android.application") version "8.1.4" apply false
            id("org.jetbrains.kotlin.android") version "1.8.10" apply false
        }
        EOF
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build Debug APK
      run: |
        gradle wrapper
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace --info
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: bitchat-simple-apk
        path: app/build/outputs/apk/debug/app-debug.apk